#!/usr/bin/env bash
# Generates /etc/apache2/conf-available/cloudflare-remoteip.conf from
# Cloudflare's currently published edge ranges, so REMOTE_ADDR is the
# real visitor rather than a Cloudflare edge node.
#
# Why this matters for this app specifically: both throttles key on the
# client IP. Without this, MAX_SUBMISSIONS_PER_HOUR_PER_IP becomes a
# site-wide cap (every visitor shares a handful of Cloudflare IPs), and
# one admin mistyping their password locks out every other admin.
#
#   sudo scripts/cloudflare-remoteip.sh
#   sudo a2enmod remoteip
#   sudo a2enconf cloudflare-remoteip
#   sudo systemctl reload apache2
#
# Re-run it whenever Cloudflare changes its ranges -- monthly from cron
# is reasonable, and it only reloads Apache when the file actually
# changed:
#
#   0 4 1 * * root /var/www/university-outreach/scripts/cloudflare-remoteip.sh --quiet
#
# Only run this if the origin is actually behind Cloudflare. Trusting
# these ranges while the origin is directly reachable means anyone who
# finds the origin IP can send their own CF-Connecting-IP header and
# hand themselves a fresh identity on every request -- which defeats
# both throttles rather than merely degrading them. Firewall 80/443 to
# these same ranges.

set -euo pipefail

IPS_V4_URL="${IPS_V4_URL:-https://www.cloudflare.com/ips-v4}"
IPS_V6_URL="${IPS_V6_URL:-https://www.cloudflare.com/ips-v6}"
OUT="${OUT:-/etc/apache2/conf-available/cloudflare-remoteip.conf}"
QUIET=0
[[ "${1:-}" == "--quiet" ]] && QUIET=1

log() { [[ "$QUIET" -eq 1 ]] || echo "$@"; }

tmp_dir="$(mktemp -d)"
trap 'rm -rf "$tmp_dir"' EXIT

log "== Fetching Cloudflare ranges =="
curl -fsS --max-time 30 "$IPS_V4_URL" -o "$tmp_dir/v4"
curl -fsS --max-time 30 "$IPS_V6_URL" -o "$tmp_dir/v6"

# Never write unvalidated content into an Apache config -- an error page
# or a truncated response would take Apache down on the next reload, and
# a partial range list would silently start trusting the wrong peers.
v4_re='^[0-9]{1,3}(\.[0-9]{1,3}){3}/[0-9]{1,2}$'
v6_re='^[0-9a-fA-F:]+/[0-9]{1,3}$'

validate() {
    local file="$1" pattern="$2" label="$3" min="$4" count=0 line
    while IFS= read -r line; do
        line="${line%$'\r'}"
        [[ -z "$line" ]] && continue
        if [[ ! "$line" =~ $pattern ]]; then
            echo "ERROR: $label list contains something that is not a CIDR: '$line'" >&2
            echo "Refusing to write $OUT." >&2
            exit 1
        fi
        count=$((count + 1))
    done < "$file"
    if [[ "$count" -lt "$min" ]]; then
        echo "ERROR: only $count $label ranges returned (expected at least $min) -- refusing to write a partial list." >&2
        exit 1
    fi
    log "  $label: $count ranges"
}

validate "$tmp_dir/v4" "$v4_re" IPv4 10
validate "$tmp_dir/v6" "$v6_re" IPv6 5

{
    echo "# Generated by scripts/cloudflare-remoteip.sh on $(date -u '+%Y-%m-%d %H:%M:%S UTC')."
    echo "# Source: $IPS_V4_URL and $IPS_V6_URL"
    echo "# Do not edit by hand -- re-run the script instead."
    echo
    echo "<IfModule mod_remoteip.c>"
    echo "    # Cloudflare sends the visitor's address here on every proxied"
    echo "    # request. Only honoured from the trusted peers listed below."
    echo "    RemoteIPHeader CF-Connecting-IP"
    echo
    echo "    # Log format that records the restored client address (%a)"
    echo "    # instead of the connection peer (%h, which would be"
    echo "    # Cloudflare). Switch a vhost's CustomLog to 'combined_cf' to"
    echo "    # use it; 'combined' still works and stays available."
    echo '    LogFormat "%a %l %u %t \"%r\" %>s %O \"%{Referer}i\" \"%{User-Agent}i\"" combined_cf'
    echo
    sed 's/^/    RemoteIPTrustedProxy /' "$tmp_dir/v4"
    sed 's/^/    RemoteIPTrustedProxy /' "$tmp_dir/v6"
    echo "</IfModule>"
} > "$tmp_dir/conf"

if [[ -f "$OUT" ]] && cmp -s "$tmp_dir/conf" "$OUT"; then
    log "== No change ($OUT is already current) =="
    exit 0
fi

if [[ -f "$OUT" ]]; then
    cp -a "$OUT" "$OUT.bak"
    log "== Previous version saved to $OUT.bak =="
fi

install -m 0644 "$tmp_dir/conf" "$OUT"
log "== Wrote $OUT =="

if command -v apache2ctl >/dev/null 2>&1; then
    if apache2ctl configtest >/dev/null 2>&1; then
        log "== configtest OK =="
        if [[ "$QUIET" -eq 1 ]]; then
            systemctl reload apache2
        else
            echo "Enable and reload with:"
            echo "  sudo a2enmod remoteip && sudo a2enconf cloudflare-remoteip"
            echo "  sudo systemctl reload apache2"
        fi
    else
        echo "ERROR: apache2ctl configtest failed after writing $OUT." >&2
        [[ -f "$OUT.bak" ]] && { cp -a "$OUT.bak" "$OUT"; echo "Restored the previous version." >&2; }
        exit 1
    fi
fi
